from __future__ import annotations

from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text
from sqlalchemy.orm import Session

from src.api.dealers import router as dealers_router
from src.api.finance import router as finance_router
from src.api.payments import router as payments_router
from src.api.payroll_credits import router as payroll_credits_router
from src.api.payroll_credits import router_alias as payroll_credits_router_alias
from src.api.stock import router as stock_router
from src.core.config import get_settings
from src.db.session import get_db

settings = get_settings()

openapi_tags = [
    {"name": "Health", "description": "Service and dependency health checks."},
    {"name": "Dealers", "description": "CRUD operations for dealer records."},
    {"name": "Stock", "description": "CRUD operations for stock entries (purchases from dealers)."},
    {"name": "Payroll/Credits", "description": "CRUD operations for dealer payroll credits and balance computation."},
    {
        "name": "Payments",
        "description": "CRUD operations for dealer payment records and paid/unpaid status handling.",
    },
    {
        "name": "Finance",
        "description": "Finance reporting endpoints (totals, per-dealer summaries, and activity feed).",
    },
]

app = FastAPI(
    title=settings.app_title,
    description="Backend API for managing dealers, stock entries, payroll credits, payments and reporting.",
    version=settings.app_version,
    openapi_tags=openapi_tags,
)

# CORS configuration:
# - Dev frontend runs at http://localhost:3000
# - Backend runs at http://localhost:3001
# - We keep credentials disabled (cookies/auth headers not required for this app in dev).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register API routers
app.include_router(dealers_router, prefix="/api")
app.include_router(stock_router, prefix="/api")
app.include_router(payroll_credits_router, prefix="/api")
app.include_router(payroll_credits_router_alias, prefix="/api")
app.include_router(payments_router, prefix="/api")
app.include_router(finance_router, prefix="/api")


@app.get(
    "/",
    tags=["Health"],
    summary="Basic health check",
    description="Returns a simple response indicating the service is running.",
    operation_id="health_check",
)
def health_check():
    """Entrypoint health check.

    Returns:
        dict: Simple message indicating service status.
    """
    return {"message": "Healthy"}


@app.get(
    "/api/health",
    tags=["Health"],
    summary="API health check (compat)",
    description="Compatibility alias for health checks when clients assume the API is mounted under /api.",
    operation_id="health_check_api_alias",
)
def health_check_api_alias():
    """Compatibility alias for health checks.

    Returns:
        dict: Same payload as the root health check.
    """
    return health_check()


@app.get(
    "/api/openapi.json",
    tags=["Health"],
    summary="OpenAPI schema (compat)",
    description="Compatibility alias for the OpenAPI schema when clients assume the API is mounted under /api.",
    operation_id="openapi_schema_api_alias",
    include_in_schema=False,
)
def openapi_schema_api_alias():
    """Compatibility alias for the OpenAPI schema.

    Returns:
        dict: The OpenAPI schema as generated by FastAPI.
    """
    return app.openapi()


@app.get(
    "/health/db",
    tags=["Health"],
    summary="Database connectivity check",
    description="Runs a simple SELECT 1 against PostgreSQL to verify connectivity.",
    operation_id="health_check_db",
)
def health_check_db(db: Session = Depends(get_db)):
    """Database health check.

    Args:
        db: SQLAlchemy Session dependency.

    Returns:
        dict: Status plus a simple echo value from the DB.
    """
    value = db.execute(text("SELECT 1")).scalar_one()
    return {"database": "ok", "select_1": int(value)}
